export type FlowEmailTemplate = {
  id: string;
  title: string;
  audience: "customer" | "internal";
  flowTrigger: string;
  subject: string;
  previewText: string;
  body: string;
  setupSteps: string[];
  variables: string[];
};

export const FLOW_EMAIL_TEMPLATES: FlowEmailTemplate[] = [
  {
    id: "first-purchase-welcome",
    title: "First purchase wellness welcome",
    audience: "customer",
    flowTrigger: "Order created -> customer orders count equals 1 -> send email after order confirmation",
    subject: "Welcome to Living Well Today, {{ customer.first_name | default: 'friend' }}",
    previewText: "A quick note to help you get the most from your first order.",
    body: [
      "Hi {{ customer.first_name | default: 'there' }},",
      "",
      "Thank you for choosing Living Well Today. We are grateful to be part of your wellness routine and want your first order to feel simple, supported, and thoughtfully guided.",
      "",
      "A few helpful next steps:",
      "- Review the product label and suggested use before beginning.",
      "- Keep your items in a cool, dry place unless the label says otherwise.",
      "- Save this email so you can find your order details quickly.",
      "",
      "If you have questions about your order, reply to this message and our team will help you find the right next step.",
      "",
      "Warmly,",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Open Shopify Flow and create a workflow triggered by order created.",
      "Add a condition for customers whose order count is equal to 1.",
      "Add a send-email action, paste this subject and body, then send yourself a test.",
    ],
    variables: ["{{ customer.first_name }}", "{{ order.name }}"],
  },
  {
    id: "post-purchase-education",
    title: "Customer post-purchase education",
    audience: "customer",
    flowTrigger: "Order fulfilled -> wait 3 days -> send general product-use education",
    subject: "How to get the most from your Living Well Today order {{ order.name }}",
    previewText: "Simple guidance for reviewing labels, timing, and reorder planning.",
    body: [
      "Hi {{ customer.first_name | default: 'there' }},",
      "",
      "Your Living Well Today order {{ order.name }} has been fulfilled, and we wanted to share a few practical reminders as your products arrive.",
      "",
      "For the best experience, review each label carefully, follow the suggested use from the manufacturer, and keep notes about what fits naturally into your daily routine. If your practitioner gave you separate instructions, follow that guidance first.",
      "",
      "When you are ready, you can return to your account to view your order history and reorder the items that are working well for you.",
      "",
      "Thank you for letting Living Well Today support your wellness journey.",
      "",
      "Warmly,",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create a Shopify Flow workflow triggered by order fulfilled.",
      "Add a wait step for 3 days so the note arrives after shipping movement.",
      "Use Shopify's email action or your email handoff tool with this copy.",
    ],
    variables: ["{{ customer.first_name }}", "{{ order.name }}"],
  },
  {
    id: "replenishment-reminder",
    title: "Replenishment reminder",
    audience: "customer",
    flowTrigger: "Order fulfilled -> wait 25 to 45 days depending on product size -> send reorder reminder",
    subject: "Time to review your Living Well Today routine, {{ customer.first_name | default: 'friend' }}",
    previewText: "A gentle reminder to check supply levels and reorder if needed.",
    body: [
      "Hi {{ customer.first_name | default: 'there' }},",
      "",
      "This is a friendly reminder from Living Well Today to check your current supply and see whether anything in your wellness routine is running low.",
      "",
      "If you are still using the products from order {{ order.name }}, now is a good time to review your remaining quantity, confirm the label directions, and reorder before you are completely out.",
      "",
      "You can always reply if you need help finding the same item again.",
      "",
      "With appreciation,",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create one Flow workflow per replenishment window or product group.",
      "Use a wait step after fulfillment based on typical days of supply.",
      "Add a condition to avoid sending if the customer already reordered.",
    ],
    variables: ["{{ customer.first_name }}", "{{ order.name }}"],
  },
  {
    id: "vip-thank-you",
    title: "VIP customer thank-you",
    audience: "customer",
    flowTrigger: "Order created -> customer total spent or order count crosses VIP threshold -> send thank-you",
    subject: "A personal thank-you from Living Well Today, {{ customer.first_name | default: 'friend' }}",
    previewText: "We appreciate your continued trust in our store.",
    body: [
      "Hi {{ customer.first_name | default: 'there' }},",
      "",
      "We noticed your continued trust in Living Well Today, and we wanted to send a sincere thank-you. Customers like you help us keep building a thoughtful, reliable wellness store with careful product sourcing and human support.",
      "",
      "If there is anything we can make easier for your next order, reply here and our team will take a look.",
      "",
      "Thank you again for being part of Living Well Today.",
      "",
      "Warmly,",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create a Flow workflow triggered by order created.",
      "Add a condition for lifetime spend, order count, or a VIP customer tag.",
      "Send this message once, then add a tag so the customer does not receive duplicates.",
    ],
    variables: ["{{ customer.first_name }}", "{{ order.name }}"],
  },
  {
    id: "customer-winback",
    title: "Customer winback check-in",
    audience: "customer",
    flowTrigger: "Customer has not ordered in 90 days -> send check-in or create a review task",
    subject: "Checking in from Living Well Today, {{ customer.first_name | default: 'friend' }}",
    previewText: "A simple note to help you pick up where you left off.",
    body: [
      "Hi {{ customer.first_name | default: 'there' }},",
      "",
      "It has been a little while since your last Living Well Today order, so we wanted to check in and make it easy to pick up where you left off.",
      "",
      "If you are revisiting your routine, start by reviewing what you used consistently, what you paused, and what you may need to reorder. Our team can help you find prior items if you are not sure where to look.",
      "",
      "We are here when you need us.",
      "",
      "Warmly,",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create a Flow workflow based on customer inactivity or a scheduled segment.",
      "Exclude customers who recently ordered or unsubscribed from marketing.",
      "Send a test and confirm the message feels helpful, not pushy.",
    ],
    variables: ["{{ customer.first_name }}"],
  },
  {
    id: "low-stock-internal-alert",
    title: "Low-stock internal alert",
    audience: "internal",
    flowTrigger: "Inventory quantity changed -> available quantity below threshold -> email operations team",
    subject: "Low-stock review needed for Shopify product",
    previewText: "Internal alert for products that may need supplier review or reorder planning.",
    body: [
      "Living Well Today operations alert:",
      "",
      "A product has dropped below the configured inventory threshold. Please review supplier availability, current margin, recent sales velocity, and whether the product should be paused, reordered, or featured only after stock is secure.",
      "",
      "Suggested review checklist:",
      "- Confirm supplier stock and cost.",
      "- Check recent Shopify sales velocity.",
      "- Confirm whether any email, blog, or collection promotion is currently planned.",
      "- Update the Supplier Ops Agent notes after review.",
      "",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create a Shopify Flow workflow triggered by inventory quantity changed.",
      "Add a quantity threshold condition by location or product group.",
      "Send this alert to the operations inbox and add a product tag if useful.",
    ],
    variables: ["{{ product.title }}", "{{ inventory_item.sku }}"],
  },
  {
    id: "high-value-order-review",
    title: "High-value order review",
    audience: "internal",
    flowTrigger: "Order created -> order total above review threshold -> email operations team",
    subject: "High-value order review for Living Well Today",
    previewText: "Internal review note for large orders that may need extra care.",
    body: [
      "Living Well Today operations alert:",
      "",
      "A high-value order was created and should receive an extra review before fulfillment is considered complete.",
      "",
      "Suggested review checklist:",
      "- Confirm payment and fraud risk status.",
      "- Review inventory availability for all items.",
      "- Check whether any item is supplier-limited or recently flagged by Product Ops.",
      "- Add a note if customer follow-up is needed.",
      "",
      "Living Well Today",
    ].join("\n"),
    setupSteps: [
      "Create a Shopify Flow workflow triggered by order created.",
      "Add a condition for order total above your chosen review threshold.",
      "Send this alert internally and optionally add an order tag for tracking.",
    ],
    variables: ["{{ order.name }}", "{{ order.total_price }}"],
  },
];

export function templatePlainTextForFlow(template: FlowEmailTemplate): string {
  return [
    `Title: ${template.title}`,
    `Audience: ${template.audience}`,
    `Flow trigger: ${template.flowTrigger}`,
    `Subject: ${template.subject}`,
    `Preview text: ${template.previewText}`,
    "",
    "Body:",
    template.body,
    "",
    "Setup steps:",
    ...template.setupSteps.map((step, index) => `${index + 1}. ${step}`),
    "",
    `Useful variables: ${template.variables.join(", ") || "None"}`,
  ].join("\n");
}
